-- USED IN TESTS THAT USE HSQL
CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(256) PRIMARY KEY,
  RESOURCE_IDS VARCHAR(256),
  CLIENT_SECRET VARCHAR(256),
  SCOPE VARCHAR(256),
  AUTHORIZED_GRANT_TYPES VARCHAR(256),
  WEB_SERVER_REDIRECT_URI VARCHAR(256),
  AUTHORITIES VARCHAR(256),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONAL_INFORMATION VARCHAR(4096),
  AUTOAPPROVE VARCHAR(256)
);

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(256),
  TOKEN LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME VARCHAR(256),
  CLIENT_ID VARCHAR(256)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(256),
  TOKEN LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME VARCHAR(256),
  CLIENT_ID VARCHAR(256),
  AUTHENTICATION LONGVARBINARY,
  REFRESH_TOKEN VARCHAR(256)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(256),
  TOKEN LONGVARBINARY,
  AUTHENTICATION LONGVARBINARY
);

CREATE TABLE OAUTH_CODE (
  CODE VARCHAR(256), AUTHENTICATION LONGVARBINARY
);

CREATE TABLE OAUTH_APPROVALS (
	USERID VARCHAR(256),
	CLIENTID VARCHAR(256),
	SCOPE VARCHAR(256),
	STATUS VARCHAR(10),
	EXPIRESAT TIMESTAMP,
	LASTMODIFIEDAT TIMESTAMP
);

-- CUSTOMIZED OAUTH_CLIENT_DETAILS TABLE
CREATE TABLE CLIENTDETAILS (
  APPID VARCHAR(256) PRIMARY KEY,
  RESOURCEIDS VARCHAR(256),
  APPSECRET VARCHAR(256),
  SCOPE VARCHAR(256),
  GRANTTYPES VARCHAR(256),
  REDIRECTURL VARCHAR(256),
  AUTHORITIES VARCHAR(256),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONALINFORMATION VARCHAR(4096),
  AUTOAPPROVESCOPES VARCHAR(256)
);